version: '3.9'

services:
  app:
    build: .
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydb
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

volumes:
  pgdata: