# Generated by Django 5.2.1 on 2025-05-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('dst_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('flow_duration', models.BigIntegerField(blank=True, null=True)),
                ('tot_fwd_pkts', models.IntegerField(blank=True, null=True)),
                ('tot_bwd_pkts', models.IntegerField(blank=True, null=True)),
                ('fwd_pkts_per_sec', models.FloatField(blank=True, null=True)),
                ('bwd_pkts_per_sec', models.FloatField(blank=True, null=True)),
                ('flow_byts_per_sec', models.FloatField(blank=True, null=True)),
                ('flow_pkts_per_sec', models.FloatField(blank=True, null=True)),
                ('flow_iat_mean', models.FloatField(blank=True, null=True)),
                ('flow_iat_std', models.FloatField(blank=True, null=True)),
                ('totlen_fwd_pkts', models.FloatField(blank=True, null=True)),
                ('totlen_bwd_pkts', models.FloatField(blank=True, null=True)),
                ('fwd_pkt_len_max', models.FloatField(blank=True, null=True)),
                ('fwd_pkt_len_min', models.FloatField(blank=True, null=True)),
                ('fwd_pkt_len_mean', models.FloatField(blank=True, null=True)),
                ('fwd_pkt_len_std', models.FloatField(blank=True, null=True)),
                ('bwd_pkt_len_max', models.FloatField(blank=True, null=True)),
                ('bwd_pkt_len_min', models.FloatField(blank=True, null=True)),
                ('bwd_pkt_len_mean', models.FloatField(blank=True, null=True)),
                ('bwd_pkt_len_std', models.FloatField(blank=True, null=True)),
                ('flow_iat_max', models.FloatField(blank=True, null=True)),
                ('flow_iat_min', models.FloatField(blank=True, null=True)),
                ('fwd_iat_tot', models.FloatField(blank=True, null=True)),
                ('fwd_iat_mean', models.FloatField(blank=True, null=True)),
                ('fwd_iat_std', models.FloatField(blank=True, null=True)),
                ('fwd_iat_max', models.FloatField(blank=True, null=True)),
                ('fwd_iat_min', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dash_trafficlog',
                'managed': False,
            },
        ),
    ]
